# Generated by Django 5.0.4 on 2024-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_teacher_l_link_teacher_m_link_teacher_x_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_type',
            field=models.CharField(choices=[('$', '$'), ('som', 'som')], default='som', max_length=10),
        ),
    ]
